/**
 * The quartic saturation curve, and the per-stage split that made it selectable.
 *
 * ⚠ THE FIRST TEST IS THE ONE THAT MATTERS AND IT IS NOT ABOUT THE QUARTIC.
 * Adding a third curve mode meant splitting one `vsCurve` object into a per-stage
 * pair, because the cell and the valve can now hold DIFFERENT curves. That is a
 * refactor of the shipping signal path to add an option nobody has auditioned,
 * which is exactly the shape of change that re-voices a plugin by accident — the
 * `squash` note in CLAUDE.md is the same story one level up. So the shipping
 * patch is pinned bit-identical, not merely "close".
 *
 * ⚠ THE CURVE'S OWN HEADLINE CLAIM IS PINNED TOO, and it is the one a previous
 * version of the bench script got wrong: the stage is monotone at EVERY drive.
 * `inverse()` is what `computeAutoMakeupPlan` and the live tracker solve the
 * makeup through, so a fold does not read as distortion — it reads as auto
 * makeup quietly having no answer.
 */

import test from 'node:test'
import assert from 'node:assert/strict'
import {
  processLA2ABuffer, LA2A_LEGACY_PATCH,
  TUBE_CURVE_QUARTIC, CELL_CURVE_QUARTIC, CELL_CURVE_GAINMOD,
} from '../../src/audio/la2aProcessor.js'
import {
  makeQuarticSatCurve, QUARTIC_C3, QUARTIC_C4, QUARTIC_MOORE_DRIVE,
} from '../../src/audio/dsp/quarticSatCurve.js'

const SR = 44100

/** Voiced-ish material with a bright partial, so the shaper has something to do. */
function passage(seconds = 1.5) {
  const n = Math.round(SR * seconds)
  const x = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const t = i / SR
    x[i] = 0.4 * Math.sin(2 * Math.PI * 150 * t) * (0.3 + 0.7 * Math.abs(Math.sin(2 * Math.PI * 1.7 * t)))
      + 0.08 * Math.sin(2 * Math.PI * 3300 * t)
  }
  return x
}

const render = (x, params) => processLA2ABuffer([x], SR, {
  mode: 'compress', gainDb: 0, r37: 100, mix: 1, ...params,
}).channelData[0]

const maxDiff = (a, b) => {
  let d = 0
  for (let i = 0; i < a.length; i++) d = Math.max(d, Math.abs(a[i] - b[i]))
  return d
}

/**
 * Samples from the PRE-SPLIT kernel — `ddf608d^`, the last commit before
 * `vsCurve` became `cellSatCurve` + `tubeSatCurve`.
 *
 * ⚠⚠ THESE EXIST BECAUSE THE TEST THAT USED TO LIVE HERE PROVED NOTHING. It
 * rendered twice through the NEW kernel with identical params and asserted the
 * two matched, which is a determinism check wearing a compatibility check's
 * name: any regression in building or routing the per-stage curves passes it, so
 * long as the regression is consistent. Its own comment argued a golden fixture
 * would only pin "whatever ran when it was written" — but that is exactly the
 * point of one here, because what ran then was a DIFFERENT implementation.
 * Caught by Copilot on PR #160.
 *
 * Generated by rendering `passage()` through `git show ddf608d^:…/la2aProcessor.js`.
 * Regenerate the same way if this ever needs to move, and say why in the commit.
 */
const PRE_SPLIT = {
  // The pre-split DEFAULT patch, which `LA2A_TUBESAT_PATCH` now names.
  tubesat: {
    0: [0.22318701446056366, -0.3620266914367676, -0.0993051826953888, 0.18902768194675446],
    30: [0.22318701446056366, -0.3504754602909088, -0.09784369170665741, 0.18627306818962097],
    60: [0.15089087188243866, -0.11543578654527664, -0.04624849185347557, 0.0877128541469574],
    90: [0.04675345495343208, -0.0378350093960762, -0.014622868038713932, 0.027926260605454445],
  },
  legacy: {
    0: [0.2224602997303009, -0.36507803201675415, -0.0990513414144516, 0.18896958231925964],
    30: [0.2224602997303009, -0.35372987389564514, -0.09783081710338593, 0.18624690175056458],
    60: [0.14754004776477814, -0.12348733842372894, -0.04932480305433273, 0.08876615017652512],
    90: [0.04493497312068939, -0.03917602449655533, -0.0160159133374691, 0.028238501399755478],
  },
}
const GOLDEN_IDX = [1000, 20000, 40000, 66000]

test('the per-stage split is bit-identical to the kernel it replaced', async () => {
  const m = await import('../../src/audio/la2aProcessor.js')
  const x = passage()
  for (const [name, patch] of [['tubesat', m.LA2A_TUBESAT_PATCH], ['legacy', LA2A_LEGACY_PATCH]]) {
    for (const [pr, want] of Object.entries(PRE_SPLIT[name])) {
      const y = render(x, { peakReduction: Number(pr), ...patch })
      GOLDEN_IDX.forEach((idx, k) => {
        assert.equal(y[idx], want[k],
          `${name} @ PR ${pr}, sample ${idx}: ${y[idx]} against the pre-split ${want[k]}`)
      })
    }
  }
})

test('the quartic is selectable at each stage independently', () => {
  const x = passage()
  /**
   * ⚠ CONTRASTED AGAINST AN EXPLICIT `vocalsat`, NOT AGAINST THE DEFAULT. This
   * test read `render(x, {})` as the non-quartic side until the quartic became
   * the default, at which point both sides of every comparison were the same
   * curve and the test asserted that the quartic differs from itself. A test
   * that names both configurations cannot rot that way.
   */
  const V = { cellCurve: 'vocalsat', tubeCurve: 'vocalsat' }
  const ship = render(x, { peakReduction: 60, ...V })
  const qCell = render(x, { peakReduction: 60, ...V, cellCurve: CELL_CURVE_QUARTIC })
  const qValve = render(x, { peakReduction: 60, ...V, tubeCurve: TUBE_CURVE_QUARTIC })
  const qBoth = render(x, {
    peakReduction: 60, cellCurve: CELL_CURVE_QUARTIC, tubeCurve: TUBE_CURVE_QUARTIC,
  })

  assert.ok(maxDiff(ship, qCell) > 1e-4, 'selecting the quartic at the cell changed nothing')
  assert.ok(maxDiff(ship, qValve) > 1e-6, 'selecting the quartic at the valve changed nothing')
  /**
   * ⚠ THE PAIR MUST DIFFER FROM EACH SINGLE, which is the whole point of the
   * per-stage split. While one object served both stages, asking for the quartic
   * at one of them silently moved the other too, and every one of these four
   * renders would have collapsed into two.
   */
  assert.ok(maxDiff(qBoth, qCell) > 1e-6, 'valve selection did not survive a cell selection')
  assert.ok(maxDiff(qBoth, qValve) > 1e-4, 'cell selection did not survive a valve selection')

  // The cell is the loud one: ~95% of the distortion lives there.
  assert.ok(maxDiff(ship, qCell) > maxDiff(ship, qValve),
    'the cell should move the output further than the valve')
})

test('the quartic is monotone at every drive, so auto makeup always has an inverse', () => {
  /**
   * The cell's drive is `cellCurveDriveMax * comp * (1 - exp(-GR/tau))`, and
   * `comp` reaches 12 dB, so the effective drive at the default 1.5 runs to
   * about 6 — and the bench is free to set the knob to 24. 40 covers it.
   */
  for (const drive of [0.25, 1, QUARTIC_MOORE_DRIVE, 6, 12, 40]) {
    const c = makeQuarticSatCurve({ drive })
    assert.ok(c.minSlope > 0.8,
      `drive ${drive} presents slope ${c.minSlope} — the stage folds and inverse() breaks`)
    for (let v = -0.9; v <= 0.9; v += 0.1) {
      const back = c.inverse(c.transfer(v))
      assert.ok(Math.abs(back - v) < 1e-6,
        `inverse did not round-trip at drive ${drive}, x ${v.toFixed(1)}`)
    }
  }
})

test('drive cancels out of the slope, which is why there is no depth ceiling', () => {
  /**
   * ⚠ THE PROPERTY A WHOLE SESSION'S WORTH OF WRONG CONCLUSIONS TURNED ON. The
   * stage is `g(d·x)/d`, so d(f)/dx = g'(d·x) and the drive is not in it. Pin the
   * consequence directly: the minimum slope is the SAME number at every drive.
   */
  const slopes = [0.5, 1, 3, 9, 27].map(d => makeQuarticSatCurve({ drive: d }).minSlope)
  for (const s of slopes) {
    assert.ok(Math.abs(s - slopes[0]) < 1e-12,
      `minimum slope moved with drive (${slopes.join(', ')}) — the domain guard is in the wrong variable`)
  }
})

test('the identification still reproduces the readings it was fitted from', () => {
  /**
   * The constants are a transcription of a measurement, so they get the same
   * treatment `la2a-h2-refit.mjs` gives its anchor: re-derived here rather than
   * trusted, from the dev log's own columns. Small-signal closed form for
   * `u + c3·u³ + c4·u⁴` under A·sin is H2/H1 = c4·A³/2 and H4/H1 = c4·A³/8.
   */
  const dbc = r => 20 * Math.log10(Math.abs(r))
  const amp = d => Math.pow(10, d / 20)
  const measured = { '-40': -155.7, '-18': -89.7, '-1': -38.7, 9.2: -8.1 }
  for (const [level, want] of Object.entries(measured)) {
    const got = dbc(QUARTIC_C4 * Math.pow(amp(Number(level)), 3) / 2)
    assert.ok(Math.abs(got - want) < 0.1,
      `H2 at ${level} dBFS: predicted ${got.toFixed(2)}, LALA measured ${want}`)
  }
  const h4 = dbc(QUARTIC_C4 * Math.pow(amp(-18), 3) / 8)
  assert.ok(Math.abs(h4 - -101.8) < 0.1, `H4 at −18 dBFS: predicted ${h4.toFixed(2)}, measured −101.8`)
  // H3 comes from the cubic: H3/H1 = c3·A²/4.
  const h3 = dbc(QUARTIC_C3 * Math.pow(amp(-18), 2) / 4)
  assert.ok(Math.abs(h3 - -107.2) < 0.1, `H3 at −18 dBFS: predicted ${h3.toFixed(2)}, measured −107.2`)
})

test('an unknown curve name falls back to what ships, not to something older', () => {
  /**
   * ⚠ THE KERNEL ALREADY CARRIED THIS RULE FOR TWO MODES AND THE THIRD MUST NOT
   * BREAK IT — see the note on `tubeCurveMode`. A typo or a stale stored param
   * must land on the shipping curve; a fallback that lands anywhere else is not
   * a fallback.
   */
  const x = passage(0.5)
  const ship = render(x, { peakReduction: 60 })
  const typo = render(x, { peakReduction: 60, cellCurve: 'quartics', tubeCurve: 'vocalsatt' })
  assert.equal(maxDiff(ship, typo), 0, 'an unknown curve name did not fall back to the shipping curve')
})

test('the quartic ships at both stages, and the previous voicing is recoverable', async () => {
  /**
   * ⚠ THE PATCH HAS TO CARRY THE DRIVES, NOT JUST THE CURVE NAMES.
   * `CELL_CURVE_DRIVE_MAX` moved 1.5 → 5 with the curve, so a patch that restored
   * only `cellCurve: 'vocalsat'` would give Tube Saturation's curve at three times
   * the drive it was voiced at — a configuration that never shipped. That is the
   * silent-partial-restore bug `fet1176Curve.test.js` documents on the other
   * plugin, and this is the same guard one plugin over.
   */
  const m = await import('../../src/audio/la2aProcessor.js')
  assert.equal(m.LA2A_KERNEL_DEFAULTS.cellCurve, CELL_CURVE_QUARTIC)
  assert.equal(m.LA2A_KERNEL_DEFAULTS.tubeCurve, TUBE_CURVE_QUARTIC)
  assert.equal(m.CELL_CURVE_DRIVE_MAX, 5)

  for (const key of ['tubeCurve', 'cellCurve', 'cellCurveDriveMax', 'vocalSatCurveDrive', 'emphasis']) {
    assert.ok(key in m.LA2A_TUBESAT_PATCH,
      `LA2A_TUBESAT_PATCH must carry '${key}' or it restores half a voicing`)
  }
  assert.equal(m.LA2A_TUBESAT_PATCH.cellCurveDriveMax, 1.5,
    'the previous voicing was cut at cell drive 1.5, not at whatever ships now')

  // And the bench must be able to set every key it carries, same rule as the FET's.
  const t = await import('../../src/audio/effects/la2aTuning.js')
  for (const key of Object.keys(m.LA2A_TUBESAT_PATCH)) {
    assert.ok(key in t.LA2A_TUNING_DEFAULTS,
      `LA2A_TUBESAT_PATCH carries '${key}' but the bench has no default for it`)
  }

  // It must actually render differently from what now ships.
  const x = passage(0.7)
  assert.ok(maxDiff(render(x, { peakReduction: 60 }),
    render(x, { peakReduction: 60, ...m.LA2A_TUBESAT_PATCH })) > 1e-4,
  'LA2A_TUBESAT_PATCH renders identically to the shipping patch — it is not restoring anything')
})

test('the curve change did not move gain reduction, so presets need no re-cut', () => {
  /**
   * ⚠ THE LOAD-BEARING REASON THE FACTORY PRESETS SURVIVED A RE-VOICING UNTOUCHED.
   * The detector sits ahead of the gain cell and never sees the shaper, so swapping
   * the curve cannot move the envelope. `OPTO_SMOOTH_PARAM_KEYS` stores knob
   * positions and no curve keys, so a preset means the same gain reduction it
   * always did. If this ever fails, every OptoSmooth preset has silently drifted
   * and needs the `fet-recut-presets.mjs` treatment.
   */
  const x = passage()
  for (const pr of [30, 45, 55, 60, 65, 75]) {
    const base = { mode: 'compress', peakReduction: pr, gainDb: 0, r37: 100, mix: 1 }
    const ship = processLA2ABuffer([x], SR, base).metering
    for (const patch of [{ cellCurve: CELL_CURVE_QUARTIC }, { cellCurve: 'vocalsat' },
      { cellCurve: CELL_CURVE_GAINMOD }, LA2A_LEGACY_PATCH]) {
      const alt = processLA2ABuffer([x], SR, { ...base, ...patch }).metering
      assert.ok(Math.abs(ship.avgGainReductionDb - alt.avgGainReductionDb) < 1e-9,
        `curve selection moved avg GR at PR ${pr}: ${ship.avgGainReductionDb} vs ${alt.avgGainReductionDb}`)
    }
  }
})
