/**
 * Run with:  npm test
 *
 * Guards the fitted Pultec cascades against the measured curves they stand in
 * for. The constants in src/audio/dsp/pultec.js are generated by
 * scripts/fit-pultec-curves.mjs; these assertions are what stop a regenerated
 * fit — or a hand edit — from quietly shipping a different EQ.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { pultecSections, pultecNetSections, PULTEC_CHARACTERS } from '../../src/audio/dsp/pultec.js'
import { magnitudeResponseDb } from '../../src/audio/dsp/biquad.js'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..')

/** Rates the fit was solved over; see FIT_RATES in the fit script. */
const RATES = [44100, 48000, 96000]

/**
 * Tolerance, in dB, against the measured curve.
 *
 * The fit's own worst point is 0.57 dB (thick/pre at 20 kHz, at 44.1 kHz, where
 * bilinear warping compresses the top octave into almost nothing); everything
 * else is inside 0.15 dB. This is set just above the worst case so a
 * regeneration that made any stage materially worse fails here rather than in
 * someone's ears.
 */
const TOLERANCE_DB = 0.7

function readCurves(character) {
  const path = join(ROOT, 'data/pultec_curves', `scheps_${character}_curve_data.csv`)
  const rows = readFileSync(path, 'utf8').trim().split('\n').slice(1)
  const freqs = []
  const pre = []
  const post = []
  for (const row of rows) {
    if (!row.trim()) continue
    const [f, a, b] = row.split(',').map(Number)
    freqs.push(f)
    pre.push(a)
    post.push(b)
  }
  return { freqs, pre, post }
}

for (const character of PULTEC_CHARACTERS) {
  const { freqs, pre, post } = readCurves(character)

  test(`${character}: fitted stages match the measured curves`, () => {
    for (const stage of ['pre', 'post']) {
      const target = stage === 'pre' ? pre : post
      for (const sr of RATES) {
        const db = magnitudeResponseDb(pultecSections(sr, character, stage), freqs, sr)
        for (let i = 0; i < freqs.length; i++) {
          assert.ok(
            Math.abs(db[i] - target[i]) < TOLERANCE_DB,
            `${character}/${stage} @${sr}: ${freqs[i].toFixed(0)} Hz is ` +
            `${db[i].toFixed(2)} dB, measured ${target[i].toFixed(2)} dB`,
          )
        }
      }
    }
  })

  test(`${character}: net curve carries the character the spec describes`, () => {
    // The two stages do not cancel — what survives is the preset's whole point,
    // so the numbers from the spec tables are asserted directly.
    const sr = 44100
    const probes = [30, 100, 1000, 8000, 20000]
    const db = magnitudeResponseDb(pultecNetSections(sr, character), probes, sr)
    const expected = probes.map((f, i) => {
      const k = freqs.reduce((best, x, j) => (Math.abs(x - f) < Math.abs(freqs[best] - f) ? j : best), 0)
      return pre[k] + post[k]
    })
    for (let i = 0; i < probes.length; i++) {
      assert.ok(
        Math.abs(db[i] - expected[i]) < 2 * TOLERANCE_DB,
        `${character} net @${probes[i]} Hz: ${db[i].toFixed(2)} dB, expected ` +
        `${expected[i].toFixed(2)} dB`,
      )
    }
  })
}

test('Thick is the bass-forward one and Presence the top-forward one', () => {
  // The distinction the two presets exist for. If a regenerated fit ever
  // inverted this, every other assertion here would still pass.
  const sr = 44100
  const [thick, presence] = ['thick', 'presence'].map(
    c => magnitudeResponseDb(pultecNetSections(sr, c), [100, 8000], sr),
  )
  assert.ok(thick[0] > presence[0] + 1, `Thick should net more low end: ${thick[0]} vs ${presence[0]}`)
  // Both lift the presence band; Thick's net is higher there too, so the
  // difference that names them is the low end relative to the top, not the top
  // in isolation.
  assert.ok(
    thick[0] - thick[1] > presence[0] - presence[1] + 1,
    'Thick should be more low-tilted than Presence',
  )
})

test('unknown character is a hard error, not a silent flat curve', () => {
  assert.throws(() => pultecSections(44100, 'bassier', 'pre'), /unknown Pultec stage/)
})
